### ISSUE TITLE
Static path

### ISSUE THREAD

**Issue by JulioCesarSF** [gregstein/SenseiDE#1]
Hello, how are you?

There is a default path when starting up the application.

https://github.com/gregstein/SenseiDE/blob/1e892b96ee177c8e1139bb6ad8b8f2f27ff781bf/DE%20Sensei/Sensei.cs#L467

Maybe I can take a look after work to help you.

Nice tool.

Bye,

**Comment by gregstein** [comment]
Oh my god i can't believe i left that there! Thank you so much for spotting this. That's why sharing projects is always a great idea. I will remove that harmless line and recompile the binaries.

Thank you again Julio <3

**Comment by gregstein** [comment]
Repo & Binaries updated! Thank you again for reporting.

Any help you offer is most welcomed <3
Have a great rest of your day,
