### ISSUE TITLE
Not working on Windows 7.

### ISSUE THREAD

**Issue by sapioit** [gregstein/SenseiDE#3]
Does it not work on Windows 7? The error appeared after opening the app, without any other window opening before the error.

![screenshot 11928](https://user-images.githubusercontent.com/3173159/122199216-836e4d80-cea2-11eb-9b5b-e17e5d06b7a5.png)

**Comment by gregstein** [comment]
Fixed in Version 2.2 > https://github.com/gregstein/SenseiDE/releases/tag/2.2

**Comment by sapioit** [comment]
Thank you!
