### ISSUE TITLE
Additional Settings - Improve Game Experience not working

### ISSUE THREAD

**Issue by AmanKJ** [gregstein/SenseiDE#5]
Hi,

I have just started using the app as I thought it can help me zoom out a bit in game as I have a 720p display on my laptop.
Can you please check issue. 

I set the additional settings check mark "Force restart steam" and when Sensei DE restarts the settings does not reflects.

Thank you in advance.

**Comment by gregstein** [comment]
Hello AmanKJ,

AoE2 DE is locked at 100% zoom and can not be hacked to zoom out more than that unfortunately. The additional tab represents your game profile that saves all sort of things from hotkey profiles, game settings etc., zoom level. Another thing I should explain is by default when you install the game It comes with a default 50% zoom out and you can have another 50% which is a total and max of 100% zoom out. If you want the maximum zoom make sure Shrink is at 100% meaning rescaling is disabled.

Then again there is no hack that i am aware of that grants wider zoom than 100%. About the force steam restart, It's a measure to ensure that your profile settings including zoom level, hotkey profile, etc are saved for the next time you run the game, and force them to be stored in steam cloud.

**Comment by AmanKJ** [comment]
Ok I understood.

Thanks for the clarification.
