### ISSUE TITLE
[WIN10] AOE 2 DE NO START

### ISSUE THREAD

**Issue by FrannDzs** [gregstein/SenseiDE#6]
Hello, after applying the changes with your program now the game does not start. If I can give you a log tell me and I'll send it to you.

**Comment by gregstein** [comment]
Hello,

It's the "Disable Menu Effects". Please don't use it. Now first and foremost. Turn off "Game Menu Effects" then close the tool and verify the integrity of game files through steam. Finally, try again Sensei DE without apply "Disable Menu Effects"

I am currently working on an update to Sensei DE to fix the problem so thank you for reporting <3
